// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/studyos-mobile/CardStack.tsx": () => import("../components/mockups/studyos-mobile/CardStack.tsx"),
  "./components/mockups/studyos-mobile/FocusMode.tsx": () => import("../components/mockups/studyos-mobile/FocusMode.tsx")
};
